### ISSUE TITLE
You can paste inside BorderedStyleSpinner? yaks

### ISSUE THREAD

**Issue by rhychel** [edwnmrtnz/BorderedStyleView#7]
<img width="143" alt="Screen Shot 2019-07-02 at 2 17 13 PM" src="https://user-images.githubusercontent.com/3362273/60488285-2a687780-9cd4-11e9-9a6c-c144a0a25170.png">

**Comment by raquezha** [comment]
ew hahaha. will fix

**Comment by raquezha** [comment]
this issue is fixed on version 1.6.6

see #8
